const MENSAJE_ALERTA_CRITICA = "ALERTA CRITICA, EL REACTOR SE APAGARA";
const MENSAJE_ALERTA_ESTANDAR = "ALERTA ESTANDAR, SE ACTIVARAN MECANISMOS DE ENFRIAMIENTO";
const MENSAJE_ALERTA_APAGADO = "REACTOR APAGADO";

export const Constantes = {
    MENSAJE_ALERTA_CRITICA,
    MENSAJE_ALERTA_ESTANDAR,
    MENSAJE_ALERTA_APAGADO
};
