@startuml SecuenciaBarras

!theme reddress-darkblue
scale 1.3
title *Diagrama de secuencia: creación de barras*

   participant BuilderReactorNormal
    participant Reactor
    participant AdministradorBarras

    BuilderReactorNormal ->> Reactor: setAdminBarras()
    Reactor ->> AdministradorBarras: setAadministradorBarras(new AdministradorBarras())
    BuilderReactorNormal --> AdministradorBarras: cargarBarras(100)
    AdministradorBarras --> SelectorFabricaBarra: crearBarra("Cadmio")
    SelectorFabricaBarra --> SelectorFabricaBarra: getFabrica("FabricaBarraCadmio")

    SelectorFabricaBarra --> FabricaBarraCadmio: crearBarra("Cadmio")

    AdministradorBarras --> AdministradorBarras:cargarBarras(cantBarras)
    AdministradorBarras --> AdministradorBarras:subirBarras(cantidadInput)
    Reactor --> AdministradorBarras: setBarrasDeControl(Barras[])

@enduml