@startuml SecuenciaBarras

title *Diagrama de secuencia: creación de barras*

   participant BuilderReactorNormal
    participant Reactor
    participant AdministradorBarras

    BuilderReactorNormal ->> Reactor: setAdminBarras()
    Reactor ->> AdministradorBarras: setAadministradorBarras(new AdministradorBarras())
    BuilderReactorNormal --> AdministradorBarras: cargarBarras(100)
    AdministradorBarras --> FabricaBarra: crearBarra
    FabricaBarra --> FabricaBarraCadmio: crearBarra("Cadmio")
        AdministradorBarras --> AdministradorBarras: crearBarra("cadmio")
        AdministradorBarras --> AdministradorBarras: agregarBarras(nuevasBarras)
    AdministradorBarras --> FabricaBarraCadmio:agregarBarras(nuevasBarras)
    AdministradorBarras --> Reactor: setBarrasDeControl()

@enduml