@startuml SecuenciaBarras

title *Diagrama de secuencia: creación de barras*

   participant BuilderReactorNormal
    participant Reactor
    participant AdministradorBarras

    BuilderReactorNormal ->> Reactor: setAdminBarras()
    Reactor ->> AdministradorBarras: setAadministradorBarras(new AdministradorBarras())
    BuilderReactorNormal --> AdministradorBarras: cargarBarras(100)
    AdministradorBarras --> AdministradorBarras: crearBarra("cadmio")
    AdministradorBarras --> AdministradorBarras: agregarBarras(nuevasBarras)
    AdministradorBarras --> Reactor: setBarrasDeControl()

@enduml