@startuml Tp

title "Sistema de control Central Nuclear"
!theme reddress-darkblue
scale 1.3
skinparam Linetype ortho

skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor skyBlue
skinparam titleBackgroundColor #96a2ff



interface Command {
    +ejecutar(comando: Command): void
}

class ApagarReactor {
    +ejecutar(comando: Command): void
}

class EncenderReactor {
    +ejecutar(comando: Command): void
}

class InsertarBarraDeControl {
    +ejecutar(comando: Command): void
}

class ObtenerInformacionReactor {
    +ejecutar(comando: Command): void
}

class ReportarEstado {
    +ejecutar(comando: Command): void
}

class SacarBarraDeControl {
    +ejecutar(comando: Command): void
}

abstract class Alerta {
    #tipoAlerta: TipoAlerta;
    #date: Date;
    #suscriptores: IEmpleado[];

    +constructor(tipoAlerta: TipoAlerta)
    +abstract obtenerMensajeDeAlerta(): String;
    +getTipoAlerta(): TipoAlerta;
    +setTipoAlerta(value: TipoAlerta);
    +getDate(): Date;
    +setDate(value: Date);
    +toString(): String;
    +agregarSuscriptor(suscriptor: IEmpleado): void;
    +removerSuscriptor(suscriptor: IEmpleado): void;
    +notificar(): void;
}

class AlertaApagado {
    -static instance: AlertaApagado;

    -constructor(TipoAlerta: TipoAlerta);
    +static getInstance(): AlertaApagado;
    +obtenerMensajeDeAlerta(): String;
}

class AlertaCritica {
    -static instance: AlertaCritica;

    -constructor(TipoAlerta: TipoAlerta);
    +static getInstance(): AlertaCritica;
    +obtenerMensajeDeAlerta(): String;
}

class AlertaEstandar {
    -static instance: AlertaEstandar;

    -constructor(TipoAlerta: TipoAlerta);
    +static getInstance(): AlertaEstandar;
    +obtenerMensajeDeAlerta(): String;
}

class GeneradorAlertaApagado {

}

class GeneradorAlertaCritica {

}

class GeneradorAlertaEstandar {

}

enum TipoAlerta {

}



' Relaciones
Command <|.. ApagarReactor
Command <|.. EncenderReactor
Command <|.. InsertarBarraDeControl
Command <|.u. ObtenerInformacionReactor
Command <|.u. ReportarEstado
Command <|.u. SacarBarraDeControl

Alerta <|-- AlertaApagado
Alerta <|-- AlertaCritica
Alerta <|-- AlertaEstandar

@enduml