@startuml 

title ***Sistema de control Central Nuclear***


' Procesamiento de Datos
class ComprobadorSaludReactor {
    - estaEncendido(): boolean;
    - tieneTemperaturaSegura(): boolean;
    - produceEnergiaEnRango(): boolean;
    - crearAlerta(): Alerta;
    - dispararEmergencia();
}

' Acciones automáticas de seguridad
class ModuloAccionAutomaticaSeguridad {
    + apagarPorEmergencia();
}

' Interfaz humana

'' Manejo de alertas

class Alerta {
    + constructor();
    + obtenerTipoDeAlerta(): enumTipoAlerta;
    + obtenerMensajeDeAlerta(): string;
    + obtenerTimestampDeAlerta(): Date;
}

class AlertaCritica extends Alerta {

}

class AlertaEstandar extends Alerta {

}

class NotificadorDeAlerta {
    + notificarAlerta(alerta:Alerta);
}

'' Manejo de comandos
enum ComandosDisponibles {
    BARRA_CONTROL
    REACTOR,
    REFSYS,
    RSENSOR,
    REPORTAR_ESTADO
}

class Comando {

}

class InterpreteDeComandos {
    - lanzarAccion();
    + interpretarComando();
}

' Acciones
interface Accion {

}

'' Barras de control
class ManejadorDeBarraDeControl implements Accion {
    + obtenerBarrasDisponibles(): BarraDeControl[];
    + insertarBarra();
    + quitarBarra();
}

@enduml