@startuml

title "Central Nuclear"
!theme reddress-darkblue
scale 1.3
skinparam Linetype ortho

title *Central Nuclear*
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor skyBlue
skinparam titleBackgroundColor #96a2ff

' Planta nuclear
class PlantaNuclear {
    - reactores: Reactor[];
    - operadores: Operador[];
}

' Reactor
class Reactor implements Encendible {
    - idReactor: string;
    - estado: EstadoReactor;
    - mecanimosDeControl: IMecanismoDeControl[];
    - sensores: ISensor[];
    - temperatura: number;
    + encender();
    + apagar();
}

enum EstadoReactor {
    ENCENDIDO,
    APAGADO
}

enum TipoAlerta {
    CRITICA,
    ESTANDAR
}

' Operador
class Operador {
    + iniciarReaccion(reactor: Reactor) : void
    + mantenerReaccion(reactor: Reactor) : void
    + detenerReaccion(reactor: Reactor) : void
}

'Interfaces generales
interface Encendible {
    + encender();
    + apagar();
    + estaEncendido(): boolean;
}

interface Activable {
    + estaActivo(): boolean;
    + activar();
    + desactivar();
}


'Sensores
interface ISensor implements Activable {
    + estaActivo(): boolean;
    + activar();
    + desactivar();
    + obtenerValores(): number;
}

class SensorTemperatura implements ISensor {
    ' lee en °C
    + estaActivo(): boolean;
    + activar();
    + desactivar();
    + obtenerValores(): number;
}

class SensorProduccionDeEnergia implements ISensor {
    ' lee en watts
    + estaActivo(): boolean;
    + activar();
    + desactivar();
    + obtenerValores(): number;
}

' Mecanismos de control
interface IMecanismoDeControl implements Activable {
    + estaActivo(): boolean;
    + activar();
    + desactivar();
}

'' Barra de control
class BarraDeControl implements IMecanismoDeControl {
    - material: string;
    - estado: EstadoBarraDeControl;
    - tiempoVidaUtilTotal: number;
    + estaActivo(): boolean;
    'insertar barra
    + activar(); 
    ' quitar barra
    + desactivar(); 
    + obtenerEstado(): string;
    + obtenerTiempoDeVidaRestante(): number;
}

enum EstadoBarraDeControl {
    ELIMINADA,
    INSERTADA,
    EN_DESUSO
}

'' Turbina de refrigeración
class TurbinaDeRefrigeracion implements IMecanismoDeControl {
    + estaActivo(): boolean;
    + activar(); 
    + desactivar(); 
}


' Easter egg...

class Chernobyl {
    + explotar();
}

'Relaciones
Reactor -u-o PlantaNuclear
Operador -l-o PlantaNuclear
Reactor *.. ISensor
Reactor *.. IMecanismoDeControl
Reactor -[hidden]l- Encendible
Activable -[hidden]r- IMecanismoDeControl
Activable -[hidden]l- ISensor
Reactor <.. Operador


'Notas
note right of Operador: "Mantener: verificar que los mecanismos \nse activen bajo las condiciones especificadas"
note bottom of Operador: "El reactor va a iniciar apagado, \nal iniciar reaccion cambiamos la \npropiedad EstaEncendido a true"
note bottom of SensorTemperatura: "Retorna la temperatura"
note bottom of SensorProduccionDeEnergia: "Retorna la producción de energía"
note bottom of BarraDeControl: "Retorna el estado de la barra"
note bottom of BarraDeControl: "Retorna el tiempo de vida restante de la barra"
note bottom of TurbinaDeRefrigeracion: "Retorna si la turbina está activa o no"
note bottom of IMecanismoDeControl: "Interfaz común para los mecanismos de control\nque serán utilizados para controlar la temperatura del reactor"
note bottom of Chernobyl: "¡BOOM! (Easter Egg)"

@enduml

'Cambios sugeridos en PR
'- establecer relaciones entre clases
'- cambiar nombre propiedad barra de control (remainingRodLifePct => totalRodLife), el % lo podemos resolver un método que lo calcule en base al tiempo
'- agregar clases de turbinas, condensador y generador (y alguna otra de la base de funcionamiento si consideramos que es necesaria)
'- agregar Clase operador
' agregar Interface común entre los mecanismos de control (sensor de temperatura, barras de control y turbinas de refrigeración)