const MENSAJE_ALERTA_CRITICA = "ALERTA CRITICA, EL REACTOR SE APAGARA";
const MENSAJE_ALERTA_ESTANDAR = "ALERTA ESTANDAR, SE ACTIVARAN MECANISMOS DE ENFRIAMIENTO";
const MENSAJE_ALERTA_APAGADO = "REACTOR APAGADO";
